"""milestone target_progress

Revision ID: 96bcdf7ab99e
Revises: 7f0156df1ca3
Create Date: 2026-09-20 05:47:53.648947
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96bcdf7ab99e'
down_revision: str | None = '7f0156df1ca3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('milestones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_progress', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('milestones', schema=None) as batch_op:
        batch_op.drop_column('target_progress')

    # ### end Alembic commands ###
